// Converts the PNG originals in assets-src/ into responsive AVIF + WebP files in
// public/images/, and writes their dimensions to src/data/images.generated.ts.
// Run with: npm run images
import { mkdir, writeFile } from 'node:fs/promises'
import sharp from 'sharp'

const SRC = 'assets-src'
const OUT = 'public/images'
const WIDTHS = [480, 800, 1600]

/** Regions (in original pixels) blurred before export to hide personal data. */
const images = {
  'romish-auth': {
    crop: { left: 550, top: 90, width: 780, height: 330 },
    blur: [
      { left: 600, top: 255, width: 100, height: 22 }, // Steam account name
    ],
  },
  'romish-admin': {
    blur: [{ left: 320, top: 525, width: 410, height: 432 }], // user names + Steam IDs
  },
  'romish-queue': {},
  'romish-draft': {},
  'romish-veto': {},
  'romish-match': {},
}

async function blurRegions(input, regions) {
  const composites = await Promise.all(
    regions.map(async (r) => ({
      input: await sharp(input).extract(r).blur(12).toBuffer(),
      left: r.left,
      top: r.top,
    })),
  )
  return sharp(input).composite(composites).png().toBuffer()
}

await mkdir(OUT, { recursive: true })
const manifest = {}

for (const [name, opts] of Object.entries(images)) {
  let buf = await sharp(`${SRC}/${name}.png`).png().toBuffer()
  if (opts.blur) buf = await blurRegions(buf, opts.blur)
  if (opts.crop) buf = await sharp(buf).extract(opts.crop).png().toBuffer()

  const { width, height } = await sharp(buf).metadata()
  const outWidths = [...new Set(WIDTHS.map((w) => Math.min(w, width)))]

  for (const w of outWidths) {
    const resized = sharp(buf).resize({ width: w })
    await resized.clone().avif({ quality: 55 }).toFile(`${OUT}/${name}-${w}.avif`)
    await resized.clone().webp({ quality: 78 }).toFile(`${OUT}/${name}-${w}.webp`)
  }
  manifest[name] = { width, height, widths: outWidths }
  console.log(`${name}: ${width}x${height} -> ${outWidths.join(', ')}`)
}

// Icons from the Romish helmet artwork
await sharp(`${SRC}/romish-helmet.png`).resize(96).webp({ quality: 85 }).toFile(`${OUT}/romish-helmet-96.webp`)

// Site icons from assets-src/icon-source.png (rendered from scripts/og/icon.html)
const icon = `${SRC}/icon-source.png`
await sharp(icon).resize(180).png().toFile('public/apple-touch-icon.png')
await sharp(icon).resize(192).png().toFile('public/icon-192.png')
await sharp(icon).resize(512).png().toFile('public/icon-512.png')

// favicon.ico: an ICO container holding 16, 32 and 48px PNGs
const sizes = [16, 32, 48]
const pngs = await Promise.all(sizes.map((s) => sharp(icon).resize(s).png().toBuffer()))
const header = Buffer.alloc(6 + 16 * sizes.length)
header.writeUInt16LE(0, 0)
header.writeUInt16LE(1, 2)
header.writeUInt16LE(sizes.length, 4)
let offset = header.length
sizes.forEach((s, i) => {
  const e = 6 + i * 16
  header.writeUInt8(s, e)
  header.writeUInt8(s, e + 1)
  header.writeUInt16LE(1, e + 4)
  header.writeUInt16LE(32, e + 6)
  header.writeUInt32LE(pngs[i].length, e + 8)
  header.writeUInt32LE(offset, e + 12)
  offset += pngs[i].length
})
await writeFile('public/favicon.ico', Buffer.concat([header, ...pngs]))

await writeFile(
  'src/data/images.generated.ts',
  `// Generated by scripts/optimize-images.mjs. Do not edit by hand.\nexport const imageMeta = ${JSON.stringify(manifest, null, 2)} as const\n`,
)
