// Converts the PNG originals in assets-src/ into responsive AVIF + WebP files in
// public/images/, and writes their dimensions to src/data/images.generated.ts.
// Run with: npm run images
import { mkdir, writeFile } from 'node:fs/promises'
import sharp from 'sharp'

const SRC = 'assets-src'
const OUT = 'public/images'
const WIDTHS = [800, 1600]

/** Regions (in original pixels) blurred before export to hide personal data. */
const images = {
  'romish-auth': {
    crop: { left: 550, top: 90, width: 780, height: 330 },
    blur: [
      { left: 600, top: 255, width: 100, height: 22 }, // Steam account name
    ],
  },
  'romish-admin': {
    blur: [{ left: 320, top: 525, width: 410, height: 432 }], // user names + Steam IDs
  },
  'romish-queue': {},
  'romish-draft': {},
  'romish-veto': {},
  'romish-match': {},
}

async function blurRegions(input, regions) {
  const composites = await Promise.all(
    regions.map(async (r) => ({
      input: await sharp(input).extract(r).blur(12).toBuffer(),
      left: r.left,
      top: r.top,
    })),
  )
  return sharp(input).composite(composites).png().toBuffer()
}

await mkdir(OUT, { recursive: true })
const manifest = {}

for (const [name, opts] of Object.entries(images)) {
  let buf = await sharp(`${SRC}/${name}.png`).png().toBuffer()
  if (opts.blur) buf = await blurRegions(buf, opts.blur)
  if (opts.crop) buf = await sharp(buf).extract(opts.crop).png().toBuffer()

  const { width, height } = await sharp(buf).metadata()
  const outWidths = [...new Set(WIDTHS.map((w) => Math.min(w, width)))]

  for (const w of outWidths) {
    const resized = sharp(buf).resize({ width: w })
    await resized.clone().avif({ quality: 55 }).toFile(`${OUT}/${name}-${w}.avif`)
    await resized.clone().webp({ quality: 78 }).toFile(`${OUT}/${name}-${w}.webp`)
  }
  manifest[name] = { width, height, widths: outWidths }
  console.log(`${name}: ${width}x${height} -> ${outWidths.join(', ')}`)
}

// Icons from the Romish helmet artwork
await sharp(`${SRC}/romish-helmet.png`).resize(96).webp({ quality: 85 }).toFile(`${OUT}/romish-helmet-96.webp`)

await writeFile(
  'src/data/images.generated.ts',
  `// Generated by scripts/optimize-images.mjs. Do not edit by hand.\nexport const imageMeta = ${JSON.stringify(manifest, null, 2)} as const\n`,
)
