// Generated by scripts/optimize-images.mjs. Do not edit by hand.
export interface ImageMeta {
  width: number
  height: number
  widths: readonly number[]
}

export const imageMeta: Record<string, ImageMeta> = {
  "romish-social": {
    "width": 394,
    "height": 440,
    "widths": [
      394
    ]
  },
  "romish-admin": {
    "width": 1873,
    "height": 955,
    "widths": [
      480,
      800,
      1600,
      1873
    ]
  },
  "romish-match-lab": {
    "width": 1870,
    "height": 945,
    "widths": [
      480,
      800,
      1600,
      1870
    ]
  },
  "romish-profile": {
    "width": 1870,
    "height": 945,
    "widths": [
      480,
      800,
      1600,
      1870
    ]
  },
  "romish-servers": {
    "width": 1860,
    "height": 951,
    "widths": [
      480,
      800,
      1600,
      1860
    ]
  }
}
